# Episode 2: Introducing the Docker Command Line {.nonincremental}

::: {.callout-tip icon="false" .nonincremental}
## Questions

- How do I know Docker is installed and running?
- How do I interact with Docker?
:::

::: {.callout-tip icon="false" .nonincremental}
## Objectives

- Explain how to check that Docker is installed and is ready to use.
- Demonstrate some initial Docker command line interactions.
- Use the built-in help for Docker commands.
:::

---

## Docker Command Line

Before using the CLI:

- start Docker Desktop or Docker Engine;
- on Linux, Docker may already be running;
- if your install added Docker to startup, no extra step may be needed.

::: {.callout-note}

## You May Need to Log In to Docker Hub

- Docker Desktop often prompts for Docker Hub login on startup.
- Use the app menu or system tray icon to sign in.
- You will not need Docker Hub immediately, but logging in early is convenient.


:::

## Getting Started with Docker

Open a shell and confirm the CLI is available:

```bash
docker --version
```

```output
Docker version 20.10.5, build 55c4c88
```

`docker --version` confirms the command line client is installed. To check the running Docker service as well, try:

```bash
docker container ls
```

```output
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

`docker system info` also works, but it produces much more output.

However, if you instead get a message similar to the following

```output
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

then you need to check that you have started the Docker Desktop, Docker Engine, or however else you worked through the setup instructions.

## Getting Help

Most CLI tools provide built-in help with `help`, `-h`, or `--help`. Docker follows the same pattern.


```bash
docker --help
```

Key things to notice in the help output:

- high-level management groups such as `container`, `image`, `network`, and `volume`;
- individual commands such as `run`, `pull`, `push`, `build`, and `inspect`;
- the hint: `Run 'docker COMMAND --help' for more information on a command.`


::: {.helpscroll}
```output
Usage:  docker [OPTIONS] COMMAND

A self-sufficient runtime for containers

Options:
      --config string      Location of client config files (default "/Users/vini/.docker")
  -c, --context string     Name of the context to use to connect to the daemon (overrides DOCKER_HOST env var and default context set with "docker context use")
  -D, --debug              Enable debug mode
  -H, --host list          Daemon socket(s) to connect to
  -l, --log-level string   Set the logging level ("debug"|"info"|"warn"|"error"|"fatal") (default "info")
      --tls                Use TLS; implied by --tlsverify
      --tlscacert string   Trust certs signed only by this CA (default "/Users/vini/.docker/ca.pem")
      --tlscert string     Path to TLS certificate file (default "/Users/vini/.docker/cert.pem")
      --tlskey string      Path to TLS key file (default "/Users/vini/.docker/key.pem")
      --tlsverify          Use TLS and verify the remote
  -v, --version            Print version information and quit

Management Commands:
  app*        Docker App (Docker Inc., v0.9.1-beta3)
  builder     Manage builds
  buildx*     Build with BuildKit (Docker Inc., v0.5.1-docker)
  config      Manage Docker configs
  container   Manage containers
  context     Manage contexts
  image       Manage images
  manifest    Manage Docker image manifests and manifest lists
  network     Manage networks
  node        Manage Swarm nodes
  plugin      Manage plugins
  scan*       Docker Scan (Docker Inc., v0.6.0)
  secret      Manage Docker secrets
  service     Manage services
  stack       Manage Docker stacks
  swarm       Manage Swarm
  system      Manage Docker
  trust       Manage trust on Docker images
  volume      Manage volumes

Commands:
  attach      Attach local standard input, output, and error streams to a running container
  build       Build an image from a Dockerfile
  commit      Create a new image from a container's changes
  cp          Copy files/folders between a container and the local filesystem
  create      Create a new container
  diff        Inspect changes to files or directories on a container's filesystem
  events      Get real time events from the server
  exec        Run a command in a running container
  export      Export a container's filesystem as a tar archive
  history     Show the history of an image
  images      List images
  import      Import the contents from a tarball to create a filesystem image
  info        Display system-wide information
  inspect     Return low-level information on Docker objects
  kill        Kill one or more running containers
  load        Load an image from a tar archive or STDIN
  login       Log in to a Docker registry
  logout      Log out from a Docker registry
  logs        Fetch the logs of a container
  pause       Pause all processes within one or more containers
  port        List port mappings or a specific mapping for the container
  ps          List containers
  pull        Pull an image or a repository from a registry
  push        Push an image or a repository to a registry
  rename      Rename a container
  restart     Restart one or more containers
  rm          Remove one or more containers
  rmi         Remove one or more images
  run         Run a command in a new container
  save        Save one or more images to a tar archive (streamed to STDOUT by default)
  search      Search the Docker Hub for images
  start       Start one or more stopped containers
  stats       Display a live stream of container(s) resource usage statistics
  stop        Stop one or more running containers
  tag         Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE
  top         Display the running processes of a container
  unpause     Unpause all processes within one or more containers
  update      Update configuration of one or more containers
  version     Show the Docker version information
  wait        Block until one or more containers stop, then print their exit codes

Run 'docker COMMAND --help' for more information on a command.
```

:::

## `container` Help

```bash
docker container --help  # or instead 'docker container'
```

::: {.helpscroll}


```output
Usage:  docker container COMMAND

Manage containers

Commands:
  attach      Attach local standard input, output, and error streams to a running container
  commit      Create a new image from a container's changes
  cp          Copy files/folders between a container and the local filesystem
  create      Create a new container
  diff        Inspect changes to files or directories on a container's filesystem
  exec        Run a command in a running container
  export      Export a container's filesystem as a tar archive
  inspect     Display detailed information on one or more containers
  kill        Kill one or more running containers
  logs        Fetch the logs of a container
  ls          List containers
  pause       Pause all processes within one or more containers
  port        List port mappings or a specific mapping for the container
  prune       Remove all stopped containers
  rename      Rename a container
  restart     Restart one or more containers
  rm          Remove one or more containers
  run         Run a command in a new container
  start       Start one or more stopped containers
  stats       Display a live stream of container(s) resource usage statistics
  stop        Stop one or more running containers
  top         Display the running processes of a container
  unpause     Unpause all processes within one or more containers
  update      Update configuration of one or more containers
  wait        Block until one or more containers stop, then print their exit codes

Run 'docker container COMMAND --help' for more information on a command.
```

:::

## `container ls` Help

```bash
docker container ls --help  # this one actually requires the '--help' flag
```

::: {.helpscroll}

```output
Usage:  docker container ls [OPTIONS]

List containers

Aliases:
  ls, ps, list

Options:
  -a, --all             Show all containers (default shows just running)
  -f, --filter filter   Filter output based on conditions provided
      --format string   Pretty-print containers using a Go template
  -n, --last int        Show n last created containers (includes all states) (default -1)
  -l, --latest          Show the latest created container (includes all states)
      --no-trunc        Don't truncate output
  -q, --quiet           Only display container IDs
  -s, --size            Display total file sizes
```

:::



---

## Docker Command Line Interface (CLI) Syntax

::: {.callout-note}

## Docker Command Line Interface (CLI) Syntax

This lesson uses the newer grouped Docker CLI syntax [introduced with the Docker Engine version 1.13](https://www.docker.com/blog/whats-new-in-docker-1-13/):

- `docker [command] [subcommand] [options]`
- common groups include `image` and `container`
- this form is clearer than the older flat command style

Comparing the help outputs shows that Docker supports both old and newer CLI forms.

- Older form: `docker run`
- Newer grouped form: `docker container run`

The grouped form is more descriptive and is the one used in this workshop.


:::


---

## Challenge

::: {.callout-note .challenge-callout icon="false"}

## Exploring a Command

Run `docker --help` and pick a command from the list.
Explore the help prompt for that command. Try to guess how a command would work by looking at the `Usage: `
section of the prompt.

:::


---

## Solution

::: {.callout-note .solution-callout icon="false"  collapse="true"}

## Solution

Suppose we pick the `docker image build` command:

```bash
docker image build --help
```

::: {.helpscroll}


```output
Usage:  docker image build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile

Options:
     --add-host list           Add a custom host-to-IP mapping (host:ip)
     --build-arg list          Set build-time variables
     --cache-from strings      Images to consider as cache sources
     --cgroup-parent string    Optional parent cgroup for the container
     --compress                Compress the build context using gzip
     --cpu-period int          Limit the CPU CFS (Completely Fair Scheduler) period
     --cpu-quota int           Limit the CPU CFS (Completely Fair Scheduler) quota
 -c, --cpu-shares int          CPU shares (relative weight)
     --cpuset-cpus string      CPUs in which to allow execution (0-3, 0,1)
     --cpuset-mems string      MEMs in which to allow execution (0-3, 0,1)
     --disable-content-trust   Skip image verification (default true)
 -f, --file string             Name of the Dockerfile (Default is 'PATH/Dockerfile')
     --force-rm                Always remove intermediate containers
     --iidfile string          Write the image ID to the file
     --isolation string        Container isolation technology
     --label list              Set metadata for an image
 -m, --memory bytes            Memory limit
     --memory-swap bytes       Swap limit equal to memory plus swap: '-1' to enable unlimited swap
     --network string          Set the networking mode for the RUN instructions during build (default "default")
     --no-cache                Do not use cache when building the image
     --pull                    Always attempt to pull a newer version of the image
 -q, --quiet                   Suppress the build output and print image ID on success
     --rm                      Remove intermediate containers after a successful build (default true)
     --security-opt strings    Security options
     --shm-size bytes          Size of /dev/shm
 -t, --tag list                Name and optionally a tag in the 'name:tag' format
     --target string           Set the target build stage to build.
     --ulimit ulimit           Ulimit options (default [])
```

:::

We could try to guess that the command could be run like this:

```bash
docker image build .
```


```bash
docker image build https://github.com/docker/rootfs.git
```

Where `https://github.com/docker/rootfs.git` could be any relevant URL that supports a Docker image.



:::





